
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'uk';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    home: 'Home',
    pricing: 'Pricing',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    login: 'Login',
    signUp: 'Sign Up',
    
    // Common
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    contactUsAction: 'Contact Us',
    
    // Language switcher
    language: 'Language',
    english: 'English',
    ukrainian: 'Ukrainian',
    
    // Home page
    discoverFamily: 'Discover Your',
    familyStory: 'Family Story',
    homeSubtitle: 'Build your family tree, discover your ancestors, and preserve your heritage for future generations. Start your journey into the past today.',
    startBuildingFree: 'Start Building Free',
    everythingYouNeed: 'Everything You Need to Build Your Family Tree',
    powerfulTools: 'Powerful tools and features designed to make genealogy research simple and enjoyable.',
    buildYourTree: 'Build Your Tree',
    buildTreeDesc: 'Create beautiful, interactive family trees with photos, stories, and important dates.',
    discoverAncestors: 'Discover Ancestors',
    discoverDesc: 'Search through millions of historical records to uncover your family\'s past.',
    shareCollaborate: 'Share & Collaborate',
    shareDesc: 'Invite family members to contribute and build your tree together.',
    familyTreesCreated: 'Family Trees Created',
    historicalRecords: 'Historical Records',
    activeUsers: 'Active Users',
    countriesSupported: 'Countries Supported',
    whatUsersSay: 'What Our Users Say',
    usersSubtitle: 'Join thousands of families who have discovered their heritage with us.',
    sarahTestimonial: 'I discovered relatives I never knew existed! This platform made family research so much easier.',
    michaelTestimonial: 'The interface is intuitive and the search features are powerful. Highly recommend!',
    emmaTestimonial: 'Finally found the missing piece of my family puzzle. Amazing genealogy tools!',
    readyToStart: 'Ready to Start Your Family Journey?',
    readySubtitle: 'Join millions of people discovering their family history. Start building your tree today.',
    getStartedFree: 'Get Started for Free',
    
    // Contact page
    contactUsTitle: 'Contact Us',
    contactSubtitle: 'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    getInTouch: 'Get in Touch',
    email: 'Email',
    phone: 'Phone',
    office: 'Office',
    mondayFriday: 'Monday - Friday, 9 AM - 6 PM EST',
    sendMessage: 'Send us a Message',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    subject: 'Subject',
    message: 'Message',
    yourFullName: 'Your full name',
    yourEmail: 'your.email@example.com',
    whatAbout: 'What is this about?',
    howCanHelp: 'Tell us how we can help you...',
    
    // Footer
    footerDescription: 'Discover your family history and build your family tree with our easy-to-use tools. Connect with your heritage and preserve your family\'s story for future generations.',
    quickLinks: 'Quick Links',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    cookiePolicy: 'Cookie Policy',
    footerCopyright: '© 2025 Lineage. All rights reserved. Built with love for families worldwide.',
    
    // Privacy Policy
    privacyPolicyTitle: 'Privacy Policy',
    privacySubtitle: 'Your privacy is important to us. This policy explains how we collect, use, and protect your information.',
    lastUpdated: 'Last updated:',
    informationWeCollect: '1. Information We Collect',
    informationDesc: 'We collect information you provide directly to us, such as when you create an account, build your family tree, or contact us for support.',
    personalInfo: 'Personal information (name, email address, phone number)',
    familyTreeData: 'Family tree data and genealogical information',
    profilePhotos: 'Profile photos and documents you upload',
    paymentInfo: 'Payment information for premium services',
    howWeUse: '2. How We Use Your Information',
    howWeUseDesc: 'We use the information we collect to:',
    provideServices: 'Provide and maintain our family tree building services',
    processTransactions: 'Process transactions and send related information',
    sendNotices: 'Send you technical notices and support messages',
    communicate: 'Communicate with you about products, services, and events',
    improveServices: 'Improve our services and develop new features',
    informationSharing: '3. Information Sharing',
    sharingDesc: 'We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy:',
    withConsent: 'With your explicit consent',
    legalCompliance: 'To comply with legal obligations',
    protectRights: 'To protect our rights and prevent fraud',
    serviceProviders: 'With service providers who assist our operations',
    dataSecurity: '4. Data Security',
    securityDesc: 'We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the internet is 100% secure.',
    yourRights: '5. Your Rights',
    yourRightsDesc: 'You have the right to:',
    accessUpdate: 'Access and update your personal information',
    deleteAccount: 'Delete your account and associated data',
    optOut: 'Opt out of marketing communications',
    requestCopy: 'Request a copy of your data',
    privacyContactSection: '6. Contact Us',
    privacyContact: 'If you have any questions about this Privacy Policy, please contact us at:',
    
    // Terms of Service
    termsTitle: 'Terms of Service',
    termsSubtitle: 'Please read these terms carefully before using our family tree building service.',
    acceptanceTerms: '1. Acceptance of Terms',
    acceptanceDesc: 'By accessing and using Lineage\'s family tree building service, you accept and agree to be bound by the terms and provision of this agreement.',
    useLicense: '2. Use License',
    licenseDesc: 'Permission is granted to temporarily access and use Lineage for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:',
    modifyMaterials: 'Modify or copy the materials',
    commercialUse: 'Use the materials for any commercial purpose or for any public display',
    reverseEngineer: 'Attempt to reverse engineer any software contained on the website',
    removeNotices: 'Remove any copyright or other proprietary notations from the materials',
    userAccounts: '3. User Accounts',
    accountsDesc: 'When you create an account with us, you must provide information that is accurate, complete, and current at all times. You are responsible for safeguarding the password and for all activities that occur under your account.',
    userContent: '4. User Content',
    contentDesc: 'You retain ownership of any content you submit, post, or display on or through the service. By submitting content, you grant us a worldwide, non-exclusive, royalty-free license to use, copy, reproduce, process, adapt, modify, publish, transmit, display, and distribute such content.',
    paymentTerms: '5. Payment Terms',
    paymentDesc: 'Some aspects of our service are provided for a fee. You agree to pay all applicable fees as described on the site in connection with such services selected by you.',
    prohibitedUses: '6. Prohibited Uses',
    prohibitedDesc: 'You may not use our service:',
    unlawfulPurpose: 'For any unlawful purpose or to solicit others to unlawful acts',
    violateRegulations: 'To violate any international, federal, provincial, or state regulations, rules, laws, or local ordinances',
    infringeRights: 'To infringe upon or violate our intellectual property rights or the intellectual property rights of others',
    harass: 'To harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate',
    falseInfo: 'To submit false or misleading information',
    disclaimer: '7. Disclaimer',
    disclaimerDesc: 'The information on this website is provided on an \'as is\' basis. To the fullest extent permitted by law, this Company excludes all representations, warranties, conditions and terms whether express, implied, statutory or otherwise.',
    limitations: '8. Limitations',
    limitationsDesc: 'In no event shall Lineage or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use Lineage\'s services.',
    contactInfo: '9. Contact Information',
    termsContact: 'If you have any questions about these Terms of Service, please contact us at:',
    
    // Cookie Policy
    cookieTitle: 'Cookie Policy',
    cookieSubtitle: 'Learn about how we use cookies and similar technologies on our website.',
    whatAreCookies: '1. What Are Cookies',
    cookiesDesc: 'Cookies are small text files that are placed on your computer or mobile device when you visit a website. They are widely used to make websites work more efficiently and provide information to the owners of the site.',
    howWeUseCookies: '2. How We Use Cookies',
    cookieUsageDesc: 'Lineage uses cookies for several purposes:',
    essentialCookies: 'Essential Cookies: These are necessary for the website to function properly',
    performanceCookies: 'Performance Cookies: These help us understand how visitors interact with our website',
    functionalityCookies: 'Functionality Cookies: These remember your preferences and personalize your experience',
    marketingCookies: 'Marketing Cookies: These are used to deliver relevant advertisements',
    typesOfCookies: '3. Types of Cookies We Use',
    essentialCookiesTitle: 'Essential Cookies',
    essentialDesc: 'These cookies are strictly necessary to provide you with services available through our website.',
    authCookies: 'Authentication cookies to keep you logged in',
    securityCookies: 'Security cookies to protect against fraud',
    sessionCookies: 'Session cookies to maintain your preferences during your visit',
    analyticsCookiesTitle: 'Analytics Cookies',
    analyticsDesc: 'We use analytics cookies to understand how our website is being used.',
    googleAnalytics: 'Google Analytics to track website usage',
    performanceMonitoring: 'Performance monitoring to identify and fix issues',
    marketingCookiesTitle: 'Marketing Cookies',
    marketingDesc: 'These cookies track your online activity to help advertisers deliver more relevant advertising.',
    socialCookies: 'Social media cookies for sharing content',
    advertisingCookies: 'Advertising cookies to show relevant ads',
    thirdPartyCookies: '4. Third-Party Cookies',
    thirdPartyDesc: 'Some cookies on our site are set by third-party services that appear on our pages. We use the following third-party services:',
    googleAnalyticsService: 'Google Analytics: For website analytics and performance monitoring',
    socialMedia: 'Social Media Platforms: For social sharing functionality',
    paymentProcessors: 'Payment Processors: For secure payment processing',
    managingCookies: '5. Managing Cookies',
    managingDesc: 'You can control and manage cookies in various ways:',
    browserSettings: 'Most browsers allow you to refuse cookies or delete certain cookies',
    notifications: 'You can set your browser to notify you when cookies are being set',
    optOutAnalytics: 'You can opt out of analytics cookies through our cookie preference center',
    industryOptOut: 'Some advertising cookies can be managed through industry opt-out programs',
    disablingNote: 'Please note that disabling certain cookies may impact the functionality of our website.',
    updatesPolicy: '6. Updates to This Policy',
    updatesDesc: 'We may update this Cookie Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons.',
    cookieContact: 'If you have any questions about our use of cookies, please contact us at:',
    
    // Login page
    welcomeBack: 'Welcome Back',
    signInContinue: 'Sign in to continue building your family tree',
    password: 'Password',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot your password?',
    signIn: 'Sign In',
    orContinueWith: 'Or continue with',
    google: 'Google',
    facebook: 'Facebook',
    noAccount: 'Don\'t have an account?',
    signUpFree: 'Sign up for free',
    
    // Sign Up page
    createAccount: 'Create Your Account',
    startBuilding: 'Start building your family tree today',
    firstName: 'First Name',
    lastName: 'Last Name',
    john: 'John',
    doe: 'Doe',
    johnDoeEmail: 'john.doe@example.com',
    createPassword: 'Create a strong password',
    confirmPassword: 'Confirm Password',
    confirmYourPassword: 'Confirm your password',
    agreeTerms: 'I agree to the',
    and: 'and',
    alreadyAccount: 'Already have an account?',
  },
  uk: {
    // Navigation
    home: 'Головна',
    pricing: 'Ціни',
    aboutUs: 'Про нас',
    contactUs: 'Контакти',
    login: 'Вхід',
    signUp: 'Реєстрація',
    
    // Common
    getStarted: 'Почати',
    learnMore: 'Дізнатися більше',
    contactUsAction: 'Зв\'язатися з нами',
    
    // Language switcher
    language: 'Мова',
    english: 'Англійська',
    ukrainian: 'Українська',
    
    // Home page
    discoverFamily: 'Відкрийте свою',
    familyStory: 'Родинну Історію',
    homeSubtitle: 'Будуйте своє генеалогічне дерево, відкривайте своїх предків та зберігайте родинну спадщину для майбутніх поколінь. Почніть свою подорож у минуле сьогодні.',
    startBuildingFree: 'Почати безкоштовно',
    everythingYouNeed: 'Все, що потрібно для побудови генеалогічного дерева',
    powerfulTools: 'Потужні інструменти та функції, розроблені для того, щоб зробити генеалогічні дослідження простими та приємними.',
    buildYourTree: 'Будуйте дерево',
    buildTreeDesc: 'Створюйте красиві, інтерактивні генеалогічні дерева з фотографіями, історіями та важливими датами.',
    discoverAncestors: 'Відкривайте предків',
    discoverDesc: 'Шукайте серед мільйонів історичних записів, щоб розкрити минуле своєї родини.',
    shareCollaborate: 'Діліться та співпрацюйте',
    shareDesc: 'Запрошуйте членів родини до участі та будуйте дерево разом.',
    familyTreesCreated: 'Створено генеалогічних дерев',
    historicalRecords: 'Історичних записів',
    activeUsers: 'Активних користувачів',
    countriesSupported: 'Підтримуваних країн',
    whatUsersSay: 'Що кажуть наші користувачі',
    usersSubtitle: 'Приєднуйтесь до тисяч родин, які відкрили свою спадщину з нами.',
    sarahTestimonial: 'Я відкрила родичів, про існування яких навіть не знала! Ця платформа значно полегшила родинні дослідження.',
    michaelTestimonial: 'Інтерфейс інтуїтивний, а функції пошуку потужні. Дуже рекомендую!',
    emmaTestimonial: 'Нарешті знайшла відсутню частину головоломки моєї родини. Дивовижні генеалогічні інструменти!',
    readyToStart: 'Готові почати свою родинну подорож?',
    readySubtitle: 'Приєднуйтесь до мільйонів людей, які відкривають свою родинну історію. Почніть будувати своє дерево сьогодні.',
    getStartedFree: 'Почати безкоштовно',
    
    // Contact page
    contactUsTitle: 'Зв\'язатися з нами',
    contactSubtitle: 'Ми будемо раді почути від вас. Надішліть нам повідомлення, і ми відповімо якомога швидше.',
    getInTouch: 'Зв\'язатися',
    email: 'Електронна пошта',
    phone: 'Телефон',
    office: 'Офіс',
    mondayFriday: 'Понеділок - П\'ятниця, 9:00 - 18:00',
    sendMessage: 'Надіслати повідомлення',
    fullName: 'Повне ім\'я',
    emailAddress: 'Адреса електронної пошти',
    subject: 'Тема',
    message: 'Повідомлення',
    yourFullName: 'Ваше повне ім\'я',
    yourEmail: 'ваша.пошта@приклад.com',
    whatAbout: 'Про що це?',
    howCanHelp: 'Розкажіть, як ми можемо вам допомогти...',
    
    // Footer
    footerDescription: 'Відкрийте свою родинну історію та побудуйте генеалогічне дерево за допомогою наших простих у використанні інструментів. Зв\'яжіться зі своєю спадщиною та збережіть історію своєї родини для майбутніх поколінь.',
    quickLinks: 'Швидкі посилання',
    legal: 'Правова інформація',
    privacyPolicy: 'Політика конфіденційності',
    termsOfService: 'Умови користування',
    cookiePolicy: 'Політика файлів cookie',
    footerCopyright: '© 2025 Lineage. Всі права захищені. Створено з любов\'ю для родин по всьому світу.',
    
    // Privacy Policy
    privacyPolicyTitle: 'Політика конфіденційності',
    privacySubtitle: 'Ваша конфіденційність важлива для нас. Ця політика пояснює, як ми збираємо, використовуємо та захищаємо вашу інформацію.',
    lastUpdated: 'Останнє оновлення:',
    informationWeCollect: '1. Інформація, яку ми збираємо',
    informationDesc: 'Ми збираємо інформацію, яку ви надаєте нам безпосередньо, наприклад, коли ви створюєте обліковий запис, будуєте генеалогічне дерево або звертаєтесь до нас за підтримкою.',
    personalInfo: 'Особиста інформація (ім\'я, адреса електронної пошти, номер телефону)',
    familyTreeData: 'Дані генеалогічного дерева та генеалогічна інформація',
    profilePhotos: 'Фотографії профілю та документи, які ви завантажуєте',
    paymentInfo: 'Платіжна інформація для преміум послуг',
    howWeUse: '2. Як ми використовуємо вашу інформацію',
    howWeUseDesc: 'Ми використовуємо зібрану інформацію для:',
    provideServices: 'Надання та підтримки наших послуг побудови генеалогічного дерева',
    processTransactions: 'Обробки транзакцій та надсилання пов\'язаної інформації',
    sendNotices: 'Надсилання технічних повідомлень та повідомлень підтримки',
    communicate: 'Спілкування з вами про продукти, послуги та події',
    improveServices: 'Покращення наших послуг та розробки нових функцій',
    informationSharing: '3. Обмін інформацією',
    sharingDesc: 'Ми не продаємо, не обмінюємо та не передаємо вашу особисту інформацію третім сторонам без вашої згоди, за винятком випадків, описаних у цій політиці:',
    withConsent: 'З вашою явною згодою',
    legalCompliance: 'Для дотримання правових зобов\'язань',
    protectRights: 'Для захисту наших прав та запобігання шахрайству',
    serviceProviders: 'З постачальниками послуг, які допомагають нашим операціям',
    dataSecurity: '4. Безпека даних',
    securityDesc: 'Ми впроваджуємо відповідні заходи безпеки для захисту вашої особистої інформації від несанкціонованого доступу, зміни, розкриття або знищення. Однак жоден метод передачі через інтернет не є на 100% безпечним.',
    yourRights: '5. Ваші права',
    yourRightsDesc: 'Ви маєте право:',
    accessUpdate: 'Отримати доступ та оновити свою особисту інформацію',
    deleteAccount: 'Видалити свій обліковий запис та пов\'язані дані',
    optOut: 'Відмовитися від маркетингових повідомлень',
    requestCopy: 'Запросити копію своїх даних',
    privacyContactSection: '6. Зв\'язатися з нами',
    privacyContact: 'Якщо у вас є питання щодо цієї Політики конфіденційності, будь ласка, зв\'яжіться з нами:',
    
    // Terms of Service
    termsTitle: 'Умови користування',
    termsSubtitle: 'Будь ласка, уважно прочитайте ці умови перед використанням нашого сервісу побудови генеалогічного дерева.',
    acceptanceTerms: '1. Прийняття умов',
    acceptanceDesc: 'Отримуючи доступ та використовуючи сервіс побудови генеалогічного дерева Lineage, ви приймаєте та погоджуєтесь дотримуватися умов та положень цієї угоди.',
    useLicense: '2. Ліцензія на використання',
    licenseDesc: 'Дозволяється тимчасовий доступ та використання Lineage лише для особистого, некомерційного тимчасового перегляду. Це надання ліцензії, а не передача права власності, і під цією ліцензією ви не можете:',
    modifyMaterials: 'Змінювати або копіювати матеріали',
    commercialUse: 'Використовувати матеріали для комерційних цілей або публічного показу',
    reverseEngineer: 'Намагатися реконструювати будь-яке програмне забезпечення, що міститься на веб-сайті',
    removeNotices: 'Видаляти будь-які авторські права або інші позначення власності з матеріалів',
    userAccounts: '3. Облікові записи користувачів',
    accountsDesc: 'Коли ви створюєте обліковий запис у нас, ви повинні надати інформацію, яка є точною, повною та актуальною в будь-який час. Ви несете відповідальність за збереження пароля та за всі дії, що відбуваються під вашим обліковим записом.',
    userContent: '4. Користувацький контент',
    contentDesc: 'Ви зберігаєте право власності на будь-який контент, який ви подаєте, публікуєте або відображаєте в сервісі або через нього. Подаючи контент, ви надаєте нам всесвітню, неексклюзивну, безплатну ліцензію на використання, копіювання, відтворення, обробку, адаптацію, модифікацію, публікацію, передачу, відображення та розповсюдження такого контенту.',
    paymentTerms: '5. Умови оплати',
    paymentDesc: 'Деякі аспекти нашого сервісу надаються за плату. Ви погоджуєтесь сплачувати всі відповідні збори, як описано на сайті, у зв\'язку з такими послугами, обраними вами.',
    prohibitedUses: '6. Заборонені використання',
    prohibitedDesc: 'Ви не можете використовувати наш сервіс:',
    unlawfulPurpose: 'Для будь-яких незаконних цілей або для спонукання інших до незаконних дій',
    violateRegulations: 'Для порушення будь-яких міжнародних, федеральних, провінційних або державних норм, правил, законів чи місцевих постанов',
    infringeRights: 'Для порушення або порушення наших прав інтелектуальної власності або прав інтелектуальної власності інших',
    harass: 'Для переслідування, образ, приниження, шкоди, наклепу, дискредитації, залякування або дискримінації',
    falseInfo: 'Для подання ложної або оманливої інформації',
    disclaimer: '7. Відмова від відповідальності',
    disclaimerDesc: 'Інформація на цьому веб-сайті надається на основі "як є". У повному обсязі, дозволеному законом, ця Компанія виключає всі заяви, гарантії, умови та терміни, будь то явні, неявні, статутні чи інші.',
    limitations: '8. Обмеження',
    limitationsDesc: 'У жодному випадку Lineage або її постачальники не несуть відповідальності за будь-які збитки (включаючи, без обмежень, збитки від втрати даних або прибутку, або через переривання бізнесу), що виникають внаслідок використання або неможливості використання послуг Lineage.',
    contactInfo: '9. Контактна інформація',
    termsContact: 'Якщо у вас є питання щодо цих Умов користування, будь ласка, зв\'яжіться з нами:',
    
    // Cookie Policy
    cookieTitle: 'Політика файлів cookie',
    cookieSubtitle: 'Дізнайтеся про те, як ми використовуємо файли cookie та подібні технології на нашому веб-сайті.',
    whatAreCookies: '1. Що таке файли cookie',
    cookiesDesc: 'Файли cookie - це невеликі текстові файли, які розміщуються на вашому комп\'ютері або мобільному пристрої, коли ви відвідуєте веб-сайт. Вони широко використовуються для того, щоб веб-сайти працювали більш ефективно та надавали інформацію власникам сайту.',
    howWeUseCookies: '2. Як ми використовуємо файли cookie',
    cookieUsageDesc: 'Lineage використовує файли cookie для кількох цілей:',
    essentialCookies: 'Основні файли cookie: Вони необхідні для правильної роботи веб-сайту',
    performanceCookies: 'Файли cookie продуктивності: Вони допомагають нам зрозуміти, як відвідувачі взаємодіють з нашим веб-сайтом',
    functionalityCookies: 'Функціональні файли cookie: Вони запам\'ятовують ваші налаштування та персоналізують ваш досвід',
    marketingCookies: 'Маркетингові файли cookie: Вони використовуються для доставки релевантної реклами',
    typesOfCookies: '3. Типи файлів cookie, які ми використовуємо',
    essentialCookiesTitle: 'Основні файли cookie',
    essentialDesc: 'Ці файли cookie є суворо необхідними для надання вам послуг, доступних через наш веб-сайт.',
    authCookies: 'Файли cookie аутентифікації для підтримки вашого входу в систему',
    securityCookies: 'Файли cookie безпеки для захисту від шахрайства',
    sessionCookies: 'Сесійні файли cookie для підтримки ваших налаштувань під час відвідування',
    analyticsCookiesTitle: 'Аналітичні файли cookie',
    analyticsDesc: 'Ми використовуємо аналітичні файли cookie, щоб зрозуміти, як використовується наш веб-сайт.',
    googleAnalytics: 'Google Analytics для відстеження використання веб-сайту',
    performanceMonitoring: 'Моніторинг продуктивності для виявлення та виправлення проблем',
    marketingCookiesTitle: 'Маркетингові файли cookie',
    marketingDesc: 'Ці файли cookie відстежують вашу онлайн-активність, щоб допомогти рекламодавцям доставляти більш релевантну рекламу.',
    socialCookies: 'Файли cookie соціальних мереж для обміну контентом',
    advertisingCookies: 'Рекламні файли cookie для показу релевантних оголошень',
    thirdPartyCookies: '4. Сторонні файли cookie',
    thirdPartyDesc: 'Деякі файли cookie на нашому сайті встановлюються сторонніми службами, які з\'являються на наших сторінках. Ми використовуємо наступні сторонні служби:',
    googleAnalyticsService: 'Google Analytics: Для веб-аналітики та моніторингу продуктивності',
    socialMedia: 'Платформи соціальних мереж: Для функціональності соціального обміну',
    paymentProcessors: 'Платіжні процесори: Для безпечної обробки платежів',
    managingCookies: '5. Управління файлами cookie',
    managingDesc: 'Ви можете контролювати та управляти файлами cookie різними способами:',
    browserSettings: 'Більшість браузерів дозволяють вам відмовитися від файлів cookie або видалити певні файли cookie',
    notifications: 'Ви можете налаштувати свій браузер на сповіщення, коли встановлюються файли cookie',
    optOutAnalytics: 'Ви можете відмовитися від аналітичних файлів cookie через наш центр налаштувань файлів cookie',
    industryOptOut: 'Деякими рекламними файлами cookie можна управляти через галузеві програми відмови',
    disablingNote: 'Зверніть увагу, що відключення певних файлів cookie може вплинути на функціональність нашого веб-сайту.',
    updatesPolicy: '6. Оновлення цієї політики',
    updatesDesc: 'Ми можемо час від часу оновлювати цю Політику файлів cookie, щоб відобразити зміни в наших практиках або з інших операційних, правових або нормативних причин.',
    cookieContact: 'Якщо у вас є питання щодо нашого використання файлів cookie, будь ласка, зв\'яжіться з нами:',
    
    // Login page
    welcomeBack: 'З поверненням',
    signInContinue: 'Увійдіть, щоб продовжити побудову генеалогічного дерева',
    password: 'Пароль',
    enterEmail: 'Введіть вашу електронну пошту',
    enterPassword: 'Введіть ваш пароль',
    rememberMe: 'Запам\'ятати мене',
    forgotPassword: 'Забули пароль?',
    signIn: 'Увійти',
    orContinueWith: 'Або продовжити з',
    google: 'Google',
    facebook: 'Facebook',
    noAccount: 'Немає облікового запису?',
    signUpFree: 'Зареєструватися безкоштовно',
    
    // Sign Up page
    createAccount: 'Створити обліковий запис',
    startBuilding: 'Почніть будувати генеалогічне дерево сьогодні',
    firstName: 'Ім\'я',
    lastName: 'Прізвище',
    john: 'Іван',
    doe: 'Іваненко',
    johnDoeEmail: 'ivan.ivanenko@приклад.com',
    createPassword: 'Створіть надійний пароль',
    confirmPassword: 'Підтвердіть пароль',
    confirmYourPassword: 'Підтвердіть ваш пароль',
    agreeTerms: 'Я погоджуюся з',
    and: 'та',
    alreadyAccount: 'Вже маєте обліковий запис?',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};